db.alerts.drop();
db.alertgroups.drop();
db.deleted_alerts.drop();
db.entries.drop();
db.entries.ensureIndex({"entry_id": 1});
db.deleted_entries.drop();
db.events.drop();
db.deleted_events.drop();
db.incidents.drop();
db.deleted_incidents.drop();
db.alerts.ensureIndex({"updated": 1, "alert_id": 1});
db.alertgroups.ensureIndex({"alertgroup_id": 1});
db.checklists.drop();
db.checklists.ensureIndex({"checklist_id": 1});
db.files.drop();
db.files.ensureIndex({"file_id": 1});
db.alert_types.drop();
db.alert_types.ensureIndex({"alert_type_id": 1});
db.tags.drop();
db.entities.drop();
db.entities.ensureIndex({entity_id: 1});
db.entities.ensureIndex({entity_type: 1, value: 1});
db.audits.drop();
db.audits.ensureIndex({what:1});
db.audits.ensureIndex({who:1});
db.audits.ensureIndex({when:1});
db.idgenerators.drop();
db.idgenerators.insert({"collection": "alerts", "lastid": 0});
db.idgenerators.insert({"collection": "entries", "lastid": 0});
db.idgenerators.insert({"collection": "events", "lastid": 0});
db.idgenerators.insert({"collection": "incidents", "lastid": 0});
db.idgenerators.insert({"collection": "checklists", "lastid": 0});
db.idgenerators.insert({"collection": "files", "lastid": 0});
db.idgenerators.insert({"collection": "alert_types", "lastid": 0});
