FROM scot_perl

#Create log directory
RUN mkdir -p /var/log/scot
RUN mkdir -p /opt/scot

COPY install/src/scot/ /opt/scot/etc/

COPY bin/stretch.pl /opt/scot/bin/
COPY lib/ /opt/scot/lib/
COPY install/src/scot /opt/scot/etc/
COPY docker-configs/stretch/stretch.cfg.pl /opt/scot/etc/

CMD ["/usr/bin/perl", "/opt/scot/bin/stretch.pl"]
