FROM scot_perl 

# Import MongoDB public GPG key AND create a MongoDB list file
RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927
RUN echo "deb http://repo.mongodb.org/apt/ubuntu $(cat /etc/lsb-release | grep DISTRIB_CODENAME | cut -d= -f2)/mongodb-org/3.2 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-3.2.list

ENV SCRIPT = ${SCRIPT} 

COPY docker-scripts/ /scot
COPY docker-configs/ /scot

RUN mkdir -p /tmp/foo/
RUN mkdir -p /opt/scot/public/

WORKDIR /scot/
CMD perl $SCRIPT
