FROM docker.elastic.co/elasticsearch/elasticsearch:5.6.3


USER root

RUN mkdir -p /opt/scotbackup/elastic
RUN chown elasticsearch:elasticsearch config/elasticsearch.yml
RUN chown -R elasticsearch:elasticsearch /opt/scotbackup/elastic

USER elasticsearch

ADD docker-configs/elastic/elasticsearch.yml /usr/share/elasticsearch/config/
ADD docker-configs/elastic/ /

EXPOSE 9200 9300

CMD /run.sh
