
#ActiveMQ dockerfile
FROM gitlab.sandia.gov:3434/docker/ubuntu
#FROM ubuntu:16.04 


#AMQ
ENV ACTIVEMQ_VERSION 5.14.3
ENV ACTIVEMQ apache-activemq-$ACTIVEMQ_VERSION
ENV ACTIVEMQ_TCP=61616 ACTIVEMQ_AMQP=5672 ACTIVEMQ_STOMP=61613 ACTIVEMQ_MQTT=1883 ACTIVEMQ_WS=61614 ACTIVEMQ_UI=8161
ENV ACTIVEMQ_HOME /opt/activemq

ENV DEBIAN_FRONTEND=noninteractive \
    JDK_VERSION="8" \
    JDK_UPDATE="144"
ENV JAVA_HOME="/opt/jdk1.${JDK_VERSION}.0_${JDK_UPDATE}" \
    JRE_HOME="/opt/jdk1.${JDK_VERSION}.0_${JDK_UPDATE}/jre"

RUN apt-get update && apt-get dist-upgrade -y && \
  curl --silent --location --retry 3 \
   http://tfx.sandia.gov/image_repo/jdk/jdk-"${JDK_VERSION}"u"${JDK_UPDATE}"-linux-x64.tar.gz \
  | tar xz -C /opt && \
  ${JAVA_HOME}/bin/keytool --import -trustcacerts -file \
  /usr/local/share/ca-certificates/https-interception.sandia.gov.crt \
  -alias Sandia -keystore ${JAVA_HOME}/jre/lib/security/cacerts \
  -storepass changeit -noprompt && \
  update-alternatives --install "/usr/bin/java" "java" "${JRE_HOME}/bin/java" 1 && \
  update-alternatives --install "/usr/bin/javac" "javac" "${JAVA_HOME}/bin/javac" 1 && \
  update-alternatives --set java "${JRE_HOME}/bin/java" && \
  update-alternatives --set javac "${JAVA_HOME}/bin/javac" && \
  apt-get autoclean && apt-get --purge -y autoremove && \
  rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

#install amq

RUN set -x && \
    curl -s -S https://archive.apache.org/dist/activemq/$ACTIVEMQ_VERSION/$ACTIVEMQ-bin.tar.gz | tar xvz -C /opt && \
    ln -s /opt/$ACTIVEMQ $ACTIVEMQ_HOME && \
    useradd -r -M -d $ACTIVEMQ_HOME activemq && \
    chown -R activemq:activemq /opt/$ACTIVEMQ && \
    chown -h activemq:activemq $ACTIVEMQ_HOME && \
    mkdir -p /var/log/activemq && \
    touch /var/log/activemq/scot.amq.log

#Copy over SCOTAQ config stuffs    
COPY install/src/ActiveMQ/amq/scotaq/ /opt/activemq/webapps/scot


COPY install/src/ActiveMQ/amq/scotamq.xml /opt/activemq/conf/
COPY install/src/ActiveMQ/amq/jetty.xml /opt/activemq/conf/

USER activemq
WORKDIR $ACTIVEMQ_HOME
EXPOSE $ACTIVEMQ_TCP $ACTIVEMQ_AMQP $ACTIVEMQ_STOMP $ACTIVEMQ_MQTT $ACTIVEMQ_WS $ACTIVEMQ_UI



CMD ["/bin/sh", "-c", "bin/activemq console"]
