FROM node:8

RUN apt-get update && \
    apt-get install apt-utils ca-certificates curl git npm  -y \
        --no-install-recommends && \
    update-ca-certificates && \
    apt-get autoclean && \
    apt-get --purge -y autoremove && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN npm install -g gulp

WORKDIR /opt/scot/pubdev/

CMD ["gulp watch-copy"]


