FROM sandialabs/scot_perl 


ENV DEBIAN_FRONTEND="noninteractive" \
    NO_PROXY="elastic,mongodb,activemq"

RUN apt-get update && \
    apt-get install apt-utils ca-certificates curl vim  -y -f  && \
    update-ca-certificates && \ 
    apt-get autoclean && \
    apt-get --purge -y autoremove && \ 
    rm -rf /var/lib/apt/lists* /tmp/* /var/tmp/*
    

RUN mkdir -p /var/log/scot
RUN mkdir -p /opt/scot
RUN mkdir -p /opt/scot/public/cached_images
RUN mkdir -p /tmp/foo

#copy config files
COPY install/src/scot/ /opt/scot/etc/  
COPY script/ /opt/scot/script/
COPY t/ /opt/scot/t/
COPY templates/ /opt/scot/templates/ 
COPY docker-configs/scot/scot.cfg.pl /opt/scot/etc/
COPY docker-scripts/* /opt/scot/bin/
COPY docker-configs/scot/backup.cfg.pl /opt/scot/etc/
COPY docker-configs/scot/restore.cfg.pl /opt/scot/etc/

RUN groupadd -g 2060 scot && \
    useradd -r -u 1060 -g scot scot

COPY demo/ /opt/scot/demo/

#scot permissions
RUN chown -R scot:scot /opt/scot/

EXPOSE 3000 

USER scot
CMD /usr/local/bin/hypnotoad -f /opt/scot/script/Scot
