#FROM ubuntu:16.04
FROM debian:jessie-slim


ARG HTTPS_PROXY
ARG HTTP_PROXY
ARG https_proxy
ARG http_proxy
ARG no_proxy

ENV https_proxy=${https_proxy}
ENV http_proxy=${http_proxy}
ENV HTTP_PROXY=${HTTP_PROXY}
ENV HTTPS_PROXY=${HTTPS_PROXY}
ENV no_proxy=${no_proxy}
ENV NO_PROXY=${NO_PROXY}
ENV no_proxy="elastic,mongodb,scot,activemq,apache"
ENV NO_PROXY="elastic,mongodb,scot,activemq,apache"



RUN apt-get update && \
    apt-get -qy upgrade && \
    apt-get install -qy perl build-essential cpanminus perl-doc perl-base perl-modules curl vim ssmtp \ 
    perlmagick perltidy libcurses-perl libmagic-dev libxml-perl libyaml-perl libwww-mechanize-perl \
    libjson-perl libmath-gmp-perl librose-db-perl libtree-simple-perl libtask-weaken-perl libtree-simple-visitorfactory-perl \
    libalgorithm-c3-perl libapparmor-perl libarchive-zip-perl libauthen-krb5-simple-perl libauthen-sasl-perl \
    libb-hooks-endofscope-perl libb-keywords-perl libbit-vector-perl libcache-perl libcairo-perl libcarp-assert-more-perl \
    libcarp-assert-perl libcarp-clan-perl libcgi-simple-perl libcgi-emulate-psgi-perl libclass-accessor-perl libclass-c3-adopt-next-perl\
    libclass-c3-perl libclass-c3-xs-perl libclass-data-inheritable-perl libclass-errorhandler-perl libclass-factory-util-perl libclass-inspector-perl \
    libclass-singleton-perl libclone-perl libclone-pp-perl libcompress-bzip2-perl libconfig-tiny-perl libdata-dump-perl libdata-dump-perl \ 
    libdata-optlist-perl libdate-manip-perl libdatetime-format-builder-perl libdatetime-format-mysql-perl libdatetime-format-pg-perl \
    libdatetime-format-strptime-perl libdatetime-locale-perl libdatetime-perl libdatetime-timezone-perl libdbd-mysql-perl \
    libdbd-pg-perl libdbi-perl libdevel-globaldestruction-perl libdevel-stacktrace-perl libdevel-symdump-perl \
    liberror-perl libexception-class-perl libextutils-autoinstall-perl libfcgi-perl libfile-copy-recursive-perl libfile-homedir-perl \
    libfile-modified-perl libfile-nfslock-perl libfile-remove-perl libfile-searchpath-perl libfile-slurp-perl libfile-spec-perl \
    libfile-which-perl libfont-afm-perl libfreezethaw-perl libglib-perl libgnome2-canvas-perl libgnome2-perl libgnome2-vfs-perl \
    libgtk2-perl libheap-perl libhtml-clean-perl libhtml-format-perl libhtml-parser-perl libhtml-tagset-perl libhtml-template-perl \
    libhtml-tree-perl libhttp-body-perl libhttp-request-ascgi-perl libhttp-response-encoding-perl libhttp-server-simple-perl \
    libio-socket-ssl-perl libio-string-perl libio-stringy-perl libjson-perl libjson-xs-perl liblingua-stem-snowball-perl \
    liblist-moreutils-perl liblocale-gettext-perl liblwp-authen-wsse-perl libmailtools-perl libmime-types-perl \
    libmldbm-perl libmodule-corelist-perl libmodule-install-perl libmodule-scandeps-perl libmro-compat-perl libnamespace-autoclean-perl \
    libnamespace-clean-perl libnet-daemon-perl libnet-dbus-perl libnet-jabber-perl libnet-libidn-perl libnet-ssleay-perl libnet-xmpp-perl \
    libpango-perl libpar-dist-perl libparams-util-perl libparams-validate-perl libparse-cpan-meta-perl libparse-debianchangelog-perl \
    libpath-class-perl libperl-critic-perl libdbd-pg-perl libdbi-perl libpod-coverage-perl libpod-spell-perl libppi-perl libreadonly-perl \
    libreadonly-xs-perl librose-datetime-perl librose-db-object-perl librose-db-perl librose-object-perl librpc-xml-perl libscope-guard-perl \
    libscope-upper-perl libsphinx-search-perl libsql-reservedwords-perl libstring-format-perl libstring-rewriteprefix-perl libsub-exporter-perl \
    libsub-install-perl libsub-name-perl libsub-uplevel-perl libtask-weaken-perl libterm-readkey-perl libtest-exception-perl \
    libtest-longstring-perl libtest-mockobject-perl libtest-perl-critic-perl libtest-pod-coverage-perl libtest-pod-perl libtest-www-mechanize-perl \
    libtext-charwidth-perl libtext-iconv-perl libtext-simpletable-perl libtext-wrapi18n-perl libtie-ixhash-perl libtime-clock-perl \
    libtimedate-perl libtree-simple-perl libtree-simple-visitorfactory-perl libuniversal-can-perl libuniversal-isa-perl \
    liburi-fetch-perl liburi-perl libuuid-perl libvariable-magic-perl libwww-mechanize-perl libwww-perl libxml-atom-perl \ 
    libxml-dom-perl libxml-libxml-perl libxml-libxslt-perl libxml-namespacesupport-perl libxml-parser-perl libxml-perl \ 
    libxml-regexp-perl libxml-sax-expat-perl libxml-sax-perl libxml-stream-perl libxml-twig-perl libxml-xpath-perl \ 
    libxml-xslt-perl libyaml-perl libyaml-syck-perl libyaml-tiny-perl libfile-libmagic-perl liblog-log4perl-perl \ 
    libplack-perl libcurses-perl libfile-libmagic-perl libnet-xmpp-perl && \
    apt-get clean && \ 
    rm -rf /var/lib/apt/lists/*, /tmp/*, /var/tmp/*

#Install CPAN modules

#RUN cpanm --force IO::AIO AnyEvent::AIO Array::Split Data::Dumper Data::Dumper::HTML Data::Dumper::Concise Data::Clean  Data::Clean::FromJSON Daemon::Control \
#    Net::LDAP Net::SMTP::TLS Net::Stomp Net::STOMP::Client Net::IDN::Encode Net::Works::Network Net::IP Moose Moose::Role \ 
#    Moose::Util::TypeConstraints MooseX::MetaDescription::Meta::Attribute MooseX::Singleton MooseX::Emulate::Class::Accessor::Fast MooseX::Types \ 
#    MooseX::Types::Common MooseX::MethodAttributes Safe Readonly DateTime DateTime::Cron::Simple DateTime::Format::Strptime \ 
#    DateTime::Format::Natural Time::HiRes Server::Starter PSGI CGI::PSGI CGI::Compile HTTP::Server::Simple::PSGI JSON DBI Parallel::ForkManager \
#    Async::Interrupt AnyEvent AnyEvent::STOMP::Client AnyEvent::ForkManager Number::Bytes::Human Sys::RunAlone Encode FileHandle File::Slurp \
#    File::Temp File::Type HTML::Entities HTML::Scrubber HTML::Strip HTML::StripTags HTML::TreeBuilder HTML::FromText HTML::FormatText \
#    MIME::Base64 IPC::Run IO::Prompt Log::Log4perl Mail::IMAPClient Mail::IMAPClient::BodyStructure MongoDB@1.2.3 MongoDB::GridFS@1.2.3 \
#    MongoDB::GridFS::File@1.2.3 MongoDB::OID@1.2.3 Meerkat Mojo MojoX::Log::Log4perl Mojolicious::Plugin::WithCSRFProtection \ 
#    Mojolicious::Plugin::TagHelpers XML::Smart Config::Auto Data::GUID File::LibMagic List::Uniq Domain::PublicSuffix Mozilla::PublicSuffix \
#    Crypt::PBKDF2 Config::Crontab Test::JSON Math::Int128 GeoIP2  Search::Elasticsearch Term::ANSIColor Courriel Statistics::Descriptive Net::SSH::Perl \
#    Net::SFTP Lingua::EN::StopWords Data::Clone XML::Twig Mail::Send SVG::Sparkline

#Mongo stuff

#RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10 && \
#    echo "deb http://repo.mongodb.org/apt/ubuntu $(cat /etc/lsb-release | grep DISTRIB_CODENAME | cut -d= -f2)/mongodb-org/3.2 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-3.2.list && \
#    apt-get update && \
#    apt-get install -y --force-yes pwgen mongodb-org-shell mongodb-org-tools  && \
#    echo "mongodb-org-shell hold" | dpkg --set-selections 

COPY lib/ /opt/scot/lib/
COPY bin/ /opt/scot/bin/

