FROM gitlab.sandia.gov:3434/docker/ubuntu
#ActiveMQ dockerfile
#FROM ubuntu:16.04


ENV no_proxy 172.18.0.5
COPY docker-configs/mapping/mapping.sh /usr/bin/mapping.sh

CMD ["/bin/sh", "/usr/bin/mapping.sh"]
