FROM sandialabs/scot_perl

# Installation:
# Import MongoDB public GPG key AND create a MongoDB list file
RUN env | grep -i "proxy"

ENV GPG_KEYS 2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5
RUN set -ex; \
	export GNUPGHOME="$(mktemp -d)"; \
	for key in $GPG_KEYS; do \
		gpg --batch --keyserver ha.pool.sks-keyservers.net --recv-keys "$key"; \
	done; \
	gpg --batch --export $GPG_KEYS > /etc/apt/trusted.gpg.d/mongodb.gpg; \
	command -v gpgconf && gpgconf --kill all || :; \
	rm -r "$GNUPGHOME"; \
	apt-key list

ARG MONGO_PACKAGE=mongodb-org
ARG MONGO_REPO=repo.mongodb.org
ENV MONGO_PACKAGE=${MONGO_PACKAGE} MONGO_REPO=${MONGO_REPO}

ENV MONGO_MAJOR 3.6
ENV MONGO_VERSION 3.6.12
# bashbrew-architectures:amd64 arm64v8
RUN echo "deb http://$MONGO_REPO/apt/ubuntu xenial/${MONGO_PACKAGE%-unstable}/$MONGO_MAJOR multiverse" | tee "/etc/apt/sources.list.d/${MONGO_PACKAGE%-unstable}.list"


# Update apt-get sources AND install MongoDB
RUN set -x \
	&& apt-get update \
	&& apt-get install -qy --with-new-pkgs \
    ${MONGO_PACKAGE}=$MONGO_VERSION \
	${MONGO_PACKAGE}-server=$MONGO_VERSION \
	${MONGO_PACKAGE}-shell=$MONGO_VERSION \
	${MONGO_PACKAGE}-mongos=$MONGO_VERSION \
	${MONGO_PACKAGE}-tools=$MONGO_VERSION \
	&& rm -rf /var/lib/apt/lists/* \
	&& rm -rf /var/lib/mongodb \
	&& mv /etc/mongod.conf /etc/mongod.conf.orig



# Create the MongoDB data directory
RUN mkdir -p /var/lib/mongodb 


# Expose port #27017 from the container to the host
EXPOSE 27017

ADD docker-configs/mongodb/mongod.conf /etc/mongod.conf
ADD docker-configs/scot/scot.cfg.pl /opt/scot/etc/
ADD docker-configs/mongodb/ /
ADD install/src/mongodb /opt/scot/install/src/mongodb

#Create log directory
RUN mkdir -p /var/log/mongodb/


#add entry scripts
RUN chmod 0755 /run.sh
RUN chmod 0755 /set_mongodb_config.sh

#ADD demo files
ADD demo/ /opt/scot/demo/

#set mongodb UID to system created
RUN usermod -u 1061 mongodb 

#add user to scot group
RUN groupadd -g 2060 scot && \
     usermod -a -G 2060 mongodb

#Set permissions for mongodb user

RUN chown -R 1061:2060 /var/log/mongodb /var/lib/mongodb/

# Set /usr/bin/mongod as the dockerized entry-point application
USER mongodb:mongodb


CMD ["/run.sh"]
