FROM sandialabs/scot_perl 

RUN apt-get update && apt-get install -y openssh-server
RUN mkdir /var/run/sshd
RUN echo 'root:screencast' | chpasswd
RUN sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

# SSH login fix. Otherwise user is kicked off after login
RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd


RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927
RUN echo "deb http://repo.mongodb.org/apt/ubuntu $(cat /etc/lsb-release | grep DISTRIB_CODENAME | cut -d= -f2)/mongodb-org/3.2 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-3.2.list

RUN apt-get update && \
    apt-get --allow-unauthenticated install -qy mongodb-org


ENV NOTVISIBLE "in users profile"
RUN echo "export VISIBLE=now" >> /etc/profile

COPY install/src/scot/ /opt/scot/etc/
COPY docker-scripts/ /opt/scot/etc/
COPY docker-configs/backup.cfg.pl /opt/scot/etc/
COPY docker-configs/restore.cfg.pl /opt/scot/etc/
COPY docker-configs/stretch/stretch.cfg.pl /opt/scot/etc/


RUN mkdir -p /tmp/foo/
RUN mkdir -p /opt/scot/public/
RUN mkdir -p /opt/scotbackup/mongo/scot-prod 
RUN mkdir -p /opt/scotbackup/cached_images
RUN mkdir -p /opt/scotbackup/elastic

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]
