// Generated by CoffeeScript 1.11.1
(function() {
  var feps, feq, fgt, fgte, flt, flte, fnz, fzero;

  feps = 0.0000001;

  feq = function(a, b) {
    return (Math.abs(a - b)) < feps;
  };

  fgt = function(a, b) {
    return (a - b) > feps;
  };

  fgte = function(a, b) {
    return ((a - b) > feps) || (feq(a, b));
  };

  flt = function(a, b) {
    return fgt(b, a);
  };

  flte = function(a, b) {
    return fgte(b, a);
  };

  fnz = function(a) {
    return !fzero(a);
  };

  fzero = function(a) {
    return feq(a, 0);
  };

  module.exports = {
    feps: feps,
    feq: feq,
    fgt: fgt,
    fgte: fgte,
    flt: flt,
    flte: flte,
    fnz: fnz,
    fzero: fzero
  };

}).call(this);

//# sourceMappingURL=eps.js.map
