// Generated by CoffeeScript 1.11.1
(function() {
  var Iterator;

  Iterator = (function() {
    function Iterator(nxt) {
      this.nxt = nxt;
      this.elt = this.nxt();
    }

    Iterator.prototype.end = function() {
      return (typeof this.elt) === "undefined";
    };

    Iterator.prototype.next = function() {
      var ret;
      if (this.end()) {
        return void 0;
      }
      ret = this.elt;
      this.elt = this.nxt();
      return ret;
    };

    Iterator.prototype.collect = function() {
      var ret;
      ret = [];
      while (!this.end()) {
        ret.push(this.next());
      }
      return ret;
    };

    Iterator.prototype.map = function(f) {
      var oldnxt;
      if (!this.end()) {
        this.elt = f(this.elt);
        oldnxt = this.nxt;
        return this.nxt = function() {
          var chk;
          chk = oldnxt();
          if ((typeof chk) !== "undefined") {
            chk = f(chk);
          }
          return chk;
        };
      }
    };

    return Iterator;

  })();

  module.exports = Iterator;

}).call(this);

//# sourceMappingURL=iter.js.map
