#!/bin/bash

### BEGIN INIT INFO
# Provides:             scot
# Required-Start:       $local_fs $syslog
# Required-Stop:        $local_fs $syslog
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    Start Scot Server
# Description:          Start Scot Server
### END INIT INFO

. /lib/lsb/init-functions

APP="SCOT"
CMD="/usr/local/bin/hypnotoad"
PIDFILE="/var/run/hypno.pid"
SCRIPT="/opt/scot/script/Scot"

OS=`lsb_release -i | cut -s -f2`

if [ $OS == "RedHatEnterpriseServer" ] || [ $OS == "CentOS" ];then
    APACHE="httpd"
else 
    APACHE="apache2"
fi

case "$1" in
    start)
        echo "Starting $APP: "
        eval $CMD $SCRIPT 
        ;;
    stop)
        echo "Stopping $APP: "
        eval $CMD -s $SCRIPT 
        ;;
    restart)
        $0 stop
        $0 start
        service $APACHE restart
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac
exit 0
