db.nextid.drop();
db.nextid.insert({"for_collection": "alertgroup","last_id": 0});
db.nextid.insert({"for_collection": "alert",    "last_id": 0});
db.nextid.insert({"for_collection": "checklist","last_id": 0});
db.nextid.insert({"for_collection": "config",   "last_id": 0});
db.nextid.insert({"for_collection": "dispatch",   "last_id": 0});
db.nextid.insert({"for_collection": "entity",   "last_id": 0});
db.nextid.insert({"for_collection": "entry",    "last_id": 0});
db.nextid.insert({"for_collection": "event",    "last_id": 0});
db.nextid.insert({"for_collection": "file",     "last_id": 0});
db.nextid.insert({"for_collection": "guide",    "last_id": 0});
db.nextid.insert({"for_collection": "history",  "last_id": 0});
db.nextid.insert({"for_collection": "incident", "last_id": 0});
db.nextid.insert({"for_collection": "intel",    "last_id": 0});
db.nextid.insert({"for_collection": "intel",    "last_id": 0});
db.nextid.insert({"for_collection": "product",   "last_id": 0});
db.nextid.insert({"for_collection": "source",   "last_id": 0});
db.nextid.insert({"for_collection": "tag",      "last_id": 0});
db.nextid.insert({"for_collection": "user",     "last_id": 2});
db.nextid.insert({"for_collection": "link",     "last_id": 0});
db.nextid.insert({"for_collection": "appearance", "last_id": 0});
db.nextid.insert({"for_collection": "entitytype", "last_id": 0});
