Notes on questions I'd like to be able to answer with viz on SCOT data

* Trends
  Are attacks trending in some way? Type of attack, target of attack,
  source of attack, etc?

* Correlations
  Do certain events tend to follow others? Is there a pattern in
  target selection that might reveal something about the attacker? Can
  I recognize and eliminate a large number of unimportant events by
  some pattern they share?

* Categorize
  Given a query that returns a bunch of stuff, I want to easily
  separate it into several categories based on some kind of
  discriminant and then see them all at the same time.

  Example: given a whole bunch of suspicious emails, run them all
  through a fuzzy text analyzer. Analyzer output should be a vector of
  characteristics, which can be fed into PCA to reduce dimensionality
  and then inserted into an n-ary space partition tree. Clusters of
  similar documents can be extracted by sorting the tree nodes by
  density and picking the nodes with highest density as the cluster
  centers, then running k-means on them to classify everything.

  Categories could be dumped into a voronoi diagram or bar chart to
  make it easy to explore them.

* Rank activity *in selected subset*
  For a large filtered/selected set of emails, quickly ascertain which
  endpoints are most active.

  Display bar chart of #hits of a pattern in traffic associated with a
  given email endpoint or hop.

  Display heat map of #hits of a pattern in an association matrix of
  host pairs who have communicated.

  heat map association matrix of communicating hosts period

* Promotions
  For a given set of events, gather up their flair and find the max
  promotion count for any flair per event, and rank them that way.

* Connections/network structure
  For a filtered event set:
  1. graph entities involved directly in each event
  2. follow flair for each entity and graph those connections
  3. Potentially continue until either number of entities is too large
     or a fixed point is reached

  This process will give a historical interaction diagram for the
  entities involved in an event set.
