// Generated by CoffeeScript 1.11.1
(function() {
  var Heatmap,
    hasProp = {}.hasOwnProperty;

  Heatmap = (function() {
    function Heatmap(boundaries) {
      if (boundaries == null) {
        boundaries = {};
      }
      this.boundaries = {};
      this.total_score = 0;
      this.setBoundaries(boundaries);
    }

    Heatmap.prototype.setBounaries = function(boundaries) {
      var bound, name, results;
      results = [];
      for (name in boundaries) {
        if (!hasProp.call(boundaries, name)) continue;
        bound = boundaries[name];
        results.push(this.boundaries[name] = {
          poly: {
            regions: bound,
            inverted: false
          },
          score: 0
        });
      }
      return results;
    };

    Heatmap.prototype.incr = function(name, amount) {
      var cell;
      if (amount == null) {
        amount = 1;
      }
      cell = this.boundaries[name];
      if (!cell) {
        throw "No such heatmap cell: " + name;
      }
      cell.score += amount;
      return this.total_score += amount;
    };

    Heatmap.prototype.populate = function(data, access) {
      var name, results, value;
      if (access == null) {
        access = function(x) {
          return x;
        };
      }
      results = [];
      for (name in data) {
        if (!hasProp.call(data, name)) continue;
        value = data[name];
        results.push(this.incr(name, access(value)));
      }
      return results;
    };

    return Heatmap;

  })();

  module.exports = Heatmap;

}).call(this);

//# sourceMappingURL=heatmap.js.map
