// Generated by CoffeeScript 1.11.1
(function() {
  var React, Visualization,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  React = require('react');

  Visualization = (function(superClass) {
    extend(Visualization, superClass);

    function Visualization(props) {
      Visualization.__super__.constructor.call(this, props);
      console.log("viz constructor");
      this.rendered = false;
      this.state = {};
    }

    Visualization.prototype.render = function() {
      var div;
      this.rendered = true;
      div = React.DOM.div;
      console.log("viz render");
      return div({
        id: "revl-vizbox"
      }, "");
    };

    Visualization.prototype.shouldComponentUpdate = function() {
      return !this.rendered;
    };

    return Visualization;

  })(React.Component);

  module.exports = React.createFactory(Visualization);

}).call(this);

//# sourceMappingURL=visualization.js.map
